name: authorize_net_sdk_plugin
description: Flutter plugin for seamless integration with the Authorize.Net payment API.
version: 0.0.4
author: Lucas César Lopes <lucascesarlopes@nagazakisofware.com.br>
homepage: https://github.com/lucascelopes/Authorize_net_sdk_plugin
repository: https://github.com/lucascelopes/Authorize_net_sdk_plugin

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.nagazakisoftware.authorize_net_sdk_plugin
        pluginClass: AuthorizeNetSdkPlugin
      ios:
        pluginClass: AuthorizeNetSdkPlugin
      web:
        pluginClass: AuthorizeNetSdkPluginWeb
        fileName: authorize_net_sdk_plugin_web.dart
